# Generated by Django 4.1.1 on 2023-04-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='pending', max_length=250),
        ),
    ]
