# Generated by Django 4.1.1 on 2023-04-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_orderitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='status',
            new_name='item_status',
        ),
    ]
