# Generated by Django 4.1.1 on 2023-04-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_status_orderitem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prod_size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
