# Generated by Django 4.1.1 on 2023-03-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('product_cat', models.CharField(default='', max_length=20)),
                ('product_description', models.CharField(max_length=700)),
                ('product_number', models.BigIntegerField()),
                ('current_stock', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product')),
                ('price', models.FloatField()),
                ('trend', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
        ),
    ]
