# Generated by Django 4.1.1 on 2023-03-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('cust_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('seller_email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('comp_name', models.CharField(max_length=100)),
                ('accholder_name', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=20)),
                ('seller_pass', models.CharField(max_length=20)),
                ('acc_number', models.BigIntegerField()),
                ('sell_pic', models.ImageField(upload_to='sellerimg/')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
